//! Command execution and metric extraction for `llama.cpp`.

use std::path::PathBuf;
use std::process::Command as ProcessCommand;
use std::time::{Instant, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::error::{Lab4Error, Lab4Result};
use crate::prompt::PromptCase;

/// Runtime configuration for a `llama.cpp` command.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LlamaRunConfig {
    /// Executable path, such as `./build/bin/llama-cli`.
    pub executable: PathBuf,
    /// GGUF model path passed to `-m`.
    pub model: PathBuf,
    /// Optional working directory for the command.
    pub working_dir: Option<PathBuf>,
    /// Experiment mode label, such as `single` or `rpc`.
    pub mode: String,
    /// Optional RPC endpoint list passed to `--rpc`.
    pub rpc_endpoints: Option<String>,
    /// Default generation limit when a prompt has no `max_tokens`.
    pub default_max_tokens: Option<u32>,
    /// Extra arguments forwarded to `llama.cpp`.
    pub extra_args: Vec<String>,
}

/// One benchmark record emitted as JSONL.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
pub struct BenchRecord {
    /// Stable case id generated by the caller.
    pub case_id: String,
    /// Prompt id from the dataset.
    pub prompt_id: String,
    /// Prompt category from the dataset.
    pub category: String,
    /// Experiment mode label, such as `single` or `rpc`.
    pub mode: String,
    /// Unix timestamp in milliseconds captured before command spawn.
    pub started_at_unix_ms: u128,
    /// Wall-clock command duration in milliseconds.
    pub duration_ms: u128,
    /// Process exit code. `None` means the process was terminated by signal.
    pub exit_code: Option<i32>,
    /// Parsed generation throughput, when present in stdout or stderr.
    pub tokens_per_second: Option<f64>,
    /// Captured stdout size in bytes.
    pub stdout_bytes: usize,
    /// Captured stderr size in bytes.
    pub stderr_bytes: usize,
    /// Full command vector for reproducibility.
    pub command: Vec<String>,
}

/// Runs one prompt through `llama.cpp` and returns a structured benchmark record.
///
/// # Errors
///
/// Returns [`Lab4Error::ClockBeforeUnixEpoch`] if a timestamp cannot be built,
/// or [`Lab4Error::CommandIo`] if the `llama.cpp` process cannot be spawned or
/// waited on.
pub fn run_llama_case(
    config: &LlamaRunConfig,
    prompt: &PromptCase,
    case_id: String,
) -> Lab4Result<BenchRecord> {
    let command_args = build_llama_args(config, prompt);
    let started_at_unix_ms = unix_time_ms()?;
    let started = Instant::now();

    let mut command = ProcessCommand::new(&config.executable);
    if let Some(working_dir) = &config.working_dir {
        command.current_dir(working_dir);
    }
    command.args(command_args.iter().skip(1));

    let output = command.output().map_err(|source| Lab4Error::CommandIo {
        program: config.executable.display().to_string(),
        source,
    })?;
    let duration_ms = started.elapsed().as_millis();
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let tokens_per_second =
        parse_tokens_per_second(&stdout).or_else(|| parse_tokens_per_second(&stderr));

    Ok(BenchRecord {
        case_id,
        prompt_id: prompt.id.clone(),
        category: prompt.category.clone(),
        mode: config.mode.clone(),
        started_at_unix_ms,
        duration_ms,
        exit_code: output.status.code(),
        tokens_per_second,
        stdout_bytes: output.stdout.len(),
        stderr_bytes: output.stderr.len(),
        command: command_args,
    })
}

/// Builds the exact command vector used for a prompt.
#[must_use]
pub fn build_llama_args(config: &LlamaRunConfig, prompt: &PromptCase) -> Vec<String> {
    let mut args = vec![
        config.executable.display().to_string(),
        "-m".to_owned(),
        config.model.display().to_string(),
        "-p".to_owned(),
        prompt.prompt.clone(),
    ];

    if let Some(max_tokens) = prompt.max_tokens.or(config.default_max_tokens) {
        args.push("-n".to_owned());
        args.push(max_tokens.to_string());
    }

    if let Some(rpc_endpoints) = &config.rpc_endpoints {
        args.push("--rpc".to_owned());
        args.push(rpc_endpoints.clone());
    }

    args.extend(config.extra_args.clone());
    args
}

/// Extracts a `tokens per second` value from llama.cpp output.
#[must_use]
pub fn parse_tokens_per_second(text: &str) -> Option<f64> {
    for line in text.lines().rev() {
        if let Some(value) = parse_line_tokens_per_second(line) {
            return Some(value);
        }
    }
    None
}

fn parse_line_tokens_per_second(line: &str) -> Option<f64> {
    let markers = ["tokens per second", "tokens/s"];
    for marker in markers {
        if let Some(marker_index) = line.find(marker) {
            let before_marker = &line[..marker_index];
            for token in before_marker
                .split(|ch: char| ch.is_whitespace() || matches!(ch, '(' | ')' | ',' | '='))
                .rev()
            {
                if let Ok(value) = token.parse::<f64>() {
                    return Some(value);
                }
            }
        }
    }
    None
}

fn unix_time_ms() -> Lab4Result<u128> {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis())
        .map_err(|_| Lab4Error::ClockBeforeUnixEpoch)
}

#[cfg(test)]
#[allow(non_snake_case)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_tokens_per_second__reads_llama_cli_output() {
        let output = "llama_print_timings: eval time = 1000.00 ms / 128 runs ( 7.81 ms per token, 128.00 tokens per second)";
        assert_eq!(parse_tokens_per_second(output), Some(128.0));
    }

    #[test]
    fn test_parse_tokens_per_second__returns_none_without_metric() {
        assert_eq!(parse_tokens_per_second("no throughput here"), None);
    }

    #[test]
    fn test_build_llama_args__includes_rpc_and_extra_args() {
        let config = LlamaRunConfig {
            executable: PathBuf::from("llama-cli"),
            model: PathBuf::from("model.gguf"),
            working_dir: None,
            mode: "rpc".to_owned(),
            rpc_endpoints: Some("192.168.1.10:50052".to_owned()),
            default_max_tokens: Some(64),
            extra_args: vec!["--threads".to_owned(), "8".to_owned()],
        };
        let prompt = PromptCase {
            id: "p1".to_owned(),
            category: "os".to_owned(),
            prompt: "Explain mmap".to_owned(),
            max_tokens: None,
        };

        let args = build_llama_args(&config, &prompt);
        assert_eq!(
            args,
            vec![
                "llama-cli",
                "-m",
                "model.gguf",
                "-p",
                "Explain mmap",
                "-n",
                "64",
                "--rpc",
                "192.168.1.10:50052",
                "--threads",
                "8"
            ]
        );
    }
}
