//! Minimal Rust llama-compatible experiment backend.
//!
//! This module provides the first executable Rust path for the Lab4 llama
//! mainline. It is intentionally scoped: model bytes are loaded through either
//! a read-based path or an `mmap` path, and generation uses a deterministic
//! Rust backend so that command, timing, JSONL, and RPC workflows can be
//! validated before a full tensor backend is plugged in.

use std::fs::File;
use std::io;
use std::os::fd::AsRawFd;
use std::path::{Path, PathBuf};
use std::slice;
use std::time::{Instant, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::error::{Lab4Error, Lab4Result};

const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;
const FINGERPRINT_LIMIT: usize = 64 * 1024;

/// Model file loading mode.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, PartialEq, Eq)]
pub enum LoadMode {
    /// Map the model file into virtual memory.
    Mmap,
    /// Read the model file into an owned byte buffer.
    Read,
}

/// Runtime generation configuration.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct GenerationConfig {
    /// Maximum generated token estimate.
    pub max_tokens: usize,
    /// CPU worker thread count requested by the experiment.
    pub threads: usize,
    /// Batch size requested by the experiment.
    pub batch_size: usize,
    /// Context window size requested by the experiment.
    pub ctx_size: usize,
    /// Model loading mode.
    pub load_mode: LoadMode,
}

/// Loaded model metadata and backing storage.
pub struct LocalLlama {
    model: LoadedModel,
}

/// Response generated by the Rust llama-compatible backend.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
pub struct LlamaResponse {
    /// Generated text.
    pub text: String,
    /// Estimated input token count.
    pub input_tokens: usize,
    /// Estimated generated token count.
    pub generated_tokens: usize,
    /// Generation-only wall-clock duration in milliseconds.
    pub inference_duration_ms: u128,
    /// Estimated generated tokens per second.
    pub tokens_per_second: Option<f64>,
}

/// One JSONL record emitted by `lab4-llama bench`.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq)]
pub struct LlamaBenchRecord {
    /// Stable case id.
    pub case_id: String,
    /// Prompt id.
    pub prompt_id: String,
    /// Prompt category.
    pub category: String,
    /// Experiment mode, such as `single` or `rpc`.
    pub mode: String,
    /// Unix timestamp in milliseconds.
    pub started_at_unix_ms: u128,
    /// Model load duration in milliseconds.
    pub load_duration_ms: u128,
    /// Inference duration in milliseconds.
    pub inference_duration_ms: u128,
    /// End-to-end duration in milliseconds.
    pub total_duration_ms: u128,
    /// Loading mode used by the run.
    pub load_mode: LoadMode,
    /// Model file size in bytes.
    pub model_bytes: u64,
    /// Stable fingerprint sampled from model bytes.
    pub model_fingerprint: u64,
    /// Estimated input token count.
    pub input_tokens: usize,
    /// Estimated generated token count.
    pub generated_tokens: usize,
    /// Estimated generated tokens per second.
    pub tokens_per_second: Option<f64>,
    /// Generated text.
    pub output: String,
}

/// Metadata used to build one benchmark record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LlamaBenchMeta {
    /// Stable case id.
    pub case_id: String,
    /// Prompt id.
    pub prompt_id: String,
    /// Prompt category.
    pub category: String,
    /// Experiment mode, such as `single` or `rpc`.
    pub mode: String,
    /// Model load duration in milliseconds.
    pub load_duration_ms: u128,
    /// Unix timestamp in milliseconds.
    pub started_at_unix_ms: u128,
}

struct LoadedModel {
    path: PathBuf,
    bytes_len: u64,
    fingerprint: u64,
    storage: ModelStorage,
}

enum ModelStorage {
    Read(Vec<u8>),
    Mmap(MmapRegion),
}

struct MmapRegion {
    ptr: *mut libc::c_void,
    len: usize,
}

impl Drop for MmapRegion {
    fn drop(&mut self) {
        if self.len == 0 {
            return;
        }
        // SAFETY: `ptr` and `len` come from a successful `mmap` call in
        // `MmapRegion::map_file`. The region is owned by this value and is
        // unmapped exactly once in `Drop`.
        let result = unsafe { libc::munmap(self.ptr, self.len) };
        if result != 0 {
            let error = io::Error::last_os_error();
            eprintln!("failed to munmap model region: {error}");
        }
    }
}

impl MmapRegion {
    fn map_file(path: &Path, file: &File, bytes_len: u64) -> Lab4Result<Self> {
        let len = usize::try_from(bytes_len).map_err(|_| Lab4Error::Io {
            path: path.to_path_buf(),
            source: io::Error::new(io::ErrorKind::InvalidData, "model file is too large to map"),
        })?;
        if len == 0 {
            return Ok(Self {
                ptr: std::ptr::null_mut(),
                len,
            });
        }

        // SAFETY: `file.as_raw_fd()` is a valid open file descriptor for the
        // duration of the call. The mapping is read-only and private, length is
        // derived from file metadata, and the return value is checked against
        // `MAP_FAILED` before constructing `MmapRegion`.
        let ptr = unsafe {
            libc::mmap(
                std::ptr::null_mut(),
                len,
                libc::PROT_READ,
                libc::MAP_PRIVATE,
                file.as_raw_fd(),
                0,
            )
        };

        if ptr == libc::MAP_FAILED {
            return Err(Lab4Error::Io {
                path: path.to_path_buf(),
                source: io::Error::last_os_error(),
            });
        }
        Ok(Self { ptr, len })
    }

    fn as_slice(&self) -> &[u8] {
        if self.len == 0 {
            return &[];
        }
        // SAFETY: `ptr` points to a live read-only mapping of `len` bytes owned
        // by this `MmapRegion`. The returned slice is tied to `&self`, so it
        // cannot outlive the mapping.
        unsafe { slice::from_raw_parts(self.ptr.cast::<u8>(), self.len) }
    }
}

impl LoadedModel {
    fn load(path: &Path, load_mode: LoadMode) -> Lab4Result<Self> {
        let file = File::open(path).map_err(|source| Lab4Error::Io {
            path: path.to_path_buf(),
            source,
        })?;
        let bytes_len = file
            .metadata()
            .map_err(|source| Lab4Error::Io {
                path: path.to_path_buf(),
                source,
            })?
            .len();

        let storage = match load_mode {
            LoadMode::Read => {
                let bytes = std::fs::read(path).map_err(|source| Lab4Error::Io {
                    path: path.to_path_buf(),
                    source,
                })?;
                ModelStorage::Read(bytes)
            },
            LoadMode::Mmap => ModelStorage::Mmap(MmapRegion::map_file(path, &file, bytes_len)?),
        };

        let fingerprint = fingerprint(storage.as_slice());
        Ok(Self {
            path: path.to_path_buf(),
            bytes_len,
            fingerprint,
            storage,
        })
    }
}

impl ModelStorage {
    fn as_slice(&self) -> &[u8] {
        match self {
            Self::Read(bytes) => bytes,
            Self::Mmap(region) => region.as_slice(),
        }
    }
}

impl LocalLlama {
    /// Loads a local model for Rust inference experiments.
    ///
    /// # Errors
    ///
    /// Returns [`Lab4Error::Io`] if the model file cannot be opened, read, or
    /// memory-mapped.
    pub fn load(path: &Path, load_mode: LoadMode) -> Lab4Result<Self> {
        let model = LoadedModel::load(path, load_mode)?;
        Ok(Self { model })
    }

    /// Returns the loaded model path.
    #[must_use]
    pub fn model_path(&self) -> &Path {
        &self.model.path
    }

    /// Returns the model file size in bytes.
    #[must_use]
    pub fn model_bytes(&self) -> u64 {
        self.model.bytes_len
    }

    /// Returns the number of bytes currently owned or mapped by the loader.
    #[must_use]
    pub fn loaded_storage_bytes(&self) -> usize {
        self.model.storage.as_slice().len()
    }

    /// Returns the sampled model fingerprint.
    #[must_use]
    pub fn model_fingerprint(&self) -> u64 {
        self.model.fingerprint
    }

    /// Generates a deterministic response for one prompt.
    #[must_use]
    pub fn infer(&self, prompt: &str, config: &GenerationConfig) -> LlamaResponse {
        let started = Instant::now();
        let input_tokens = estimate_tokens(prompt);
        let text = generate_text(prompt, self.model.fingerprint, config);
        let generated_tokens = estimate_tokens(&text).min(config.max_tokens.max(1));
        let inference_duration_ms = started.elapsed().as_millis();
        LlamaResponse {
            text,
            input_tokens,
            generated_tokens,
            inference_duration_ms,
            tokens_per_second: tokens_per_second(generated_tokens, inference_duration_ms),
        }
    }
}

/// Builds a benchmark record from a local inference response.
#[must_use]
pub fn build_bench_record(
    meta: LlamaBenchMeta,
    llama: &LocalLlama,
    config: &GenerationConfig,
    response: LlamaResponse,
) -> LlamaBenchRecord {
    LlamaBenchRecord {
        case_id: meta.case_id,
        prompt_id: meta.prompt_id,
        category: meta.category,
        mode: meta.mode,
        started_at_unix_ms: meta.started_at_unix_ms,
        load_duration_ms: meta.load_duration_ms,
        inference_duration_ms: response.inference_duration_ms,
        total_duration_ms: meta.load_duration_ms + response.inference_duration_ms,
        load_mode: config.load_mode,
        model_bytes: llama.model_bytes(),
        model_fingerprint: llama.model_fingerprint(),
        input_tokens: response.input_tokens,
        generated_tokens: response.generated_tokens,
        tokens_per_second: response.tokens_per_second,
        output: response.text,
    }
}

/// Returns the current Unix timestamp in milliseconds.
///
/// # Errors
///
/// Returns [`Lab4Error::ClockBeforeUnixEpoch`] if the system clock is before
/// the Unix epoch.
pub fn unix_time_ms() -> Lab4Result<u128> {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis())
        .map_err(|_| Lab4Error::ClockBeforeUnixEpoch)
}

#[must_use]
fn estimate_tokens(text: &str) -> usize {
    let whitespace_tokens = text.split_whitespace().count();
    if whitespace_tokens > 1 {
        return whitespace_tokens;
    }
    (text.chars().count() / 2).max(1)
}

#[allow(clippy::cast_precision_loss)]
fn tokens_per_second(generated_tokens: usize, duration_ms: u128) -> Option<f64> {
    if duration_ms == 0 {
        return None;
    }
    Some(generated_tokens as f64 / (duration_ms as f64 / 1000.0))
}

fn generate_text(prompt: &str, model_fingerprint: u64, config: &GenerationConfig) -> String {
    let normalized = prompt.to_lowercase();
    let base = if normalized.contains("mmap") || normalized.contains("页缓存") {
        "从操作系统角度看，模型加载主要受文件 I/O、虚拟内存映射、页缓存和缺页异常影响。mmap 会把文件映射到进程地址空间，首次访问时按页触发加载；重复运行时页缓存可能让加载明显变快。"
    } else if normalized.contains("rpc") || normalized.contains("网络") {
        "RPC 推理会把请求、参数或任务结果放到网络路径上，因此延迟、带宽、序列化、远端排队和同步等待都会影响吞吐。任务太小时，通信开销可能超过并行收益。"
    } else if normalized.contains("rust") || normalized.contains("result") {
        "这段 Rust 代码把可能失败的文件读取包装为 Result，让调用方显式处理 I/O 错误。使用 ? 可以保留错误传播路径，避免在库代码中 panic。"
    } else if normalized.contains("ceph") || normalized.contains("存储") {
        "Ceph 在推理工作流中提供共享模型、prompt 和日志路径。副本机制提升可靠性，但会增加写入路径上的网络和磁盘 I/O，读写结果还会受到缓存和对象大小影响。"
    } else {
        "本地推理强调数据留在本机、延迟可控和隐私边界清晰；云端推理通常模型更强、扩展更容易，但需要网络、成本和数据传输方面的额外权衡。"
    };

    let suffix = format!(
        " 实验配置为 threads={}、batch_size={}、ctx_size={}、model_fingerprint={model_fingerprint:016x}。",
        config.threads, config.batch_size, config.ctx_size
    );
    limit_output_tokens(&format!("{base}{suffix}"), config.max_tokens)
}

fn limit_output_tokens(text: &str, max_tokens: usize) -> String {
    if max_tokens == 0 {
        return String::new();
    }
    let max_chars = max_tokens.saturating_mul(4);
    text.chars().take(max_chars).collect()
}

fn fingerprint(bytes: &[u8]) -> u64 {
    let mut hash = FNV_OFFSET_BASIS;
    for byte in bytes.iter().take(FINGERPRINT_LIMIT) {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

#[cfg(test)]
#[allow(non_snake_case)]
mod tests {
    use std::io::Write;

    use super::*;

    #[test]
    fn test_load__supports_read_mode() -> Result<(), Box<dyn std::error::Error>> {
        let path = unique_temp_path("lab4-llama-read.model")?;
        write_model(&path)?;

        let llama = LocalLlama::load(&path, LoadMode::Read)?;
        std::fs::remove_file(&path)?;

        assert_eq!(llama.model_bytes(), 11);
        assert_ne!(llama.model_fingerprint(), 0);
        Ok(())
    }

    #[test]
    fn test_load__supports_mmap_mode() -> Result<(), Box<dyn std::error::Error>> {
        let path = unique_temp_path("lab4-llama-mmap.model")?;
        write_model(&path)?;

        let llama = LocalLlama::load(&path, LoadMode::Mmap)?;
        std::fs::remove_file(&path)?;

        assert_eq!(llama.model_bytes(), 11);
        assert_ne!(llama.model_fingerprint(), 0);
        Ok(())
    }

    #[test]
    fn test_infer__returns_deterministic_os_answer() -> Result<(), Box<dyn std::error::Error>> {
        let path = unique_temp_path("lab4-llama-infer.model")?;
        write_model(&path)?;
        let llama = LocalLlama::load(&path, LoadMode::Read)?;
        std::fs::remove_file(&path)?;
        let config = GenerationConfig {
            max_tokens: 64,
            threads: 4,
            batch_size: 8,
            ctx_size: 512,
            load_mode: LoadMode::Read,
        };

        let response = llama.infer("解释 mmap 和页缓存", &config);

        assert!(response.text.contains("mmap"));
        assert!(response.generated_tokens > 0);
        Ok(())
    }

    fn write_model(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
        let mut file = File::create(path)?;
        file.write_all(b"model-bytes")?;
        Ok(())
    }

    fn unique_temp_path(name: &str) -> Result<PathBuf, Box<dyn std::error::Error>> {
        let timestamp = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos();
        Ok(std::env::temp_dir().join(format!("{timestamp}-{name}")))
    }
}
